version: '3.8'

services:
  selenium-report-api:
    build:
      context: .
      dockerfile: SeleniumReportAPI\Dockerfile
    ports:
      - "5000:80"
    environment:
      - AppDBContextConnection=Server=db;Database=GhostQA;User=sa;Password=P@ssw0rd@123###;

  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd@123###"
      ACCEPT_EULA: "Y"