version: '3.8'

services:
  webui:
      build:
        context: .
        dockerfile: ./seleniumreact_app/Dockerfile
      ports:
        - "3000:80"
      # volumes:
        # - ./src:/app/src
        # - ./public:/app/public
      environment:
        - NODE_ENV=production
      stdin_open: true
  
  dotnetapi:
    build:
      context: .
      dockerfile: SeleniumReportAPI\Dockerfile
    ports:
      - "5000:80"
    environment:
      - AppDBContextConnection=Server=db;Database=GhostQA;User=sa;Password=P@ssw0rd@123###;

  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd@123###"
      ACCEPT_EULA: "Y"
  
  caddy:
    build:
      context: .
      dockerfile: ./compose/caddy/Dockerfile
    ports:
      - "30001:30001"
    extra_hosts:
      - host.docker.internal:host-gateway